config/routes.rb
Rails.application.routes.draw do
  root "home#show"

    delete "/logout",                to: "sessions#destroy"

    get "/repos",                  to: "repos#index"
    get "/orgs",                   to: "orgs#index"
    get "/events",                 to: "events#index"
    get "/actions",             to: "actions#index"
    get '/auth/github', as: :github_login
    get '/auth/github/callback', to: "sessions#create"

end

app/models/action.rb
class Action
  attr_reader :service

  def initialize(current_user)
    @service = GithubService.new(current_user)
  end

  def all
    temp_actions_hash = service.actions_hash
    temp_actions_hash.map do |individual_hash|
      { type: individual_hash["type"], repo: individual_hash["repo"]["name"]}
    end
  end
end

app/models/event.rb
class Event
  attr_reader :service

  def initialize(current_user)
    @service = GithubService.new(current_user)
  end

  def all
    temp_events_hash = service.events_hash
    temp_events_hash.map do |individual_hash|
      { name: individual_hash["actor"]["login"], action: individual_hash["type"], project: individual_hash["repo"]["name"]}
    end
  end
end

app/models/org.rb
class Org
  attr_reader :service

  def initialize(current_user)
    @service = GithubService.new(current_user)
  end

  def all
    temp_orgs_hash = service.orgs_hash
    temp_orgs_hash.map do |individual_hash|
      { login: individual_hash["login"]}
    end
  end

  # def save
  #   Repo.service.create_repo(self.to_h)
  # end

end

app/models/repo.rb
class Repo
  attr_reader :service

  def initialize(current_user)
    @service = GithubService.new(current_user)
  end

  def all
    temp_repos_hash = service.repos_hash
    temp_repos_hash.map do |individual_hash|
      { name: individual_hash["name" ], html_url: individual_hash["html_url"]}
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.repos
    GithubService.new(self)
  end

  def self.get_user(auth)
    User.where(provider: auth[:provider], uid: auth[:uid]).first_or_create do |user|
      user.nickname = auth[:info][:nickname]
      user.name = auth[:info][:name]
      user.email = auth[:info][:email]
      user.image = auth[:info][:image]
      user.token = auth[:credentials][:token]
      user.followers = auth[:extra][:raw_info][:followers]
      user.following = auth[:extra][:raw_info][:following]
      user.save!
    end
  end

end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController

  def index
    actions = Action.new(current_user)
    @actions = actions.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    events = Event.new(current_user)
    @events = events.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController

  def index
    org = Org.new(current_user)
    @orgs = org.all
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    repo = Repo.new(current_user)
    @repos = repo.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.get_user(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actions/index.html.erb
<ul class="actions",style="list-style: none;">
<h2>My Actions</h2>
<% @actions.each do |action| %>
<li> Event type: <%= action[:type]%> </li>
<li>Repo name: <%= action[:repo] %></li><br>
<% end %>
</ul>

app/views/events/index.html.erb
<ul class="events",style="list-style: none;">
<h2>Friends Events</h2>
<% @events.each do |event| %>
<li>User: <%= event[:name]%></li>
<li>Github Acton: <%= event[:action] %></li>
<li>Repo name: <%= event[:project] %></li><br>
<% end %>
</ul>

app/views/home/show.html.erb
<% if current_user  %>
  <h1>
    <ul style="list-style: none;">
      <li><%= image_tag(current_user.image, width: "250", height: "250") %></li>
      <li><%=  current_user.name%></li>
      <li><%=  current_user.nickname%></li>
      <li><%=  current_user.email%></li>
      <li>Followers:<%=  current_user.followers%></li>
      <li>Following:<%=  current_user.following%></li>
    </ul>
  </h1>
  <ul class="showlinks", style="list-style: none;">
    <li><%= link_to "Repositories", repos_path %></li>
    <li><%= link_to "Friends Events", events_path %></li>
    <li><%= link_to "Organizations", orgs_path %></li>
    <li><%= link_to "My Actions", actions_path %></li>
  </ul>
  <% else %>
<h1>Welcome to Github Apicurious</h1>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Github Apicurious</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% if current_user %>
      <%= link_to "Logout", logout_path, method: :delete %>
        <% else %>
        <%= link_to "Sign in with Github", github_login_path %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <title>ApiCurious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
<%= yield %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/orgs/index.html.erb
<ol class="orgs">
<h2>Organizations</h2>
<% @orgs.each do |org| %>
<li><%= org[:login]%></li>
<% end %>
</ol>

app/views/repos/index.html.erb
<ul class="repos", style="list-style: none;">
<h2>Repositories</h2>
<% @repos.each do |repo| %>
<li>
<%= link_to repo[:name], repo[:html_url]%>
</li>
<% end %>
</ul>